name: static_dom
description: A simple static HTML DOM builder library for Dart
version: 0.0.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/tejainece/static_dom

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
