name: static_dom
description: A simple static HTML DOM builder library for Dart
version: 2.0.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/tejainece/static_dom
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  ulid: ^1.0.0

dev_dependencies:
  test: 
